server {
    listen 80;
    server_name yumetunes.duckdns.org;
    
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name yumetunes.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/yumetunes.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yumetunes.duckdns.org/privkey.pem;
    client_max_body_size 50M;
    
    location /api/ {
        
        proxy_pass http://api:5000/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    location /audio/ {
        alias /usr/share/nginx/html/media/audio/;
        add_header Accept-Ranges bytes; 
    }
}





# --- NEW: Redirect HTTP to HTTPS for VocalHire ---
server {
    listen 80;
    server_name vocal-hire.duckdns.org;
    return 301 https://$host$request_uri;
}

# --- NEW: HTTPS routing for VocalHire Backend ---
server {
    listen 443 ssl;
    server_name vocal-hire.duckdns.org;

    # Point to the newly generated certs!
    ssl_certificate /etc/letsencrypt/live/vocal-hire.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vocal-hire.duckdns.org/privkey.pem;
    
    # Increase body size if users are uploading long webm audio files
    client_max_body_size 50M;

    location / {
        # How to talk to the new container? Use the Docker Host Gateway IP (usually 172.17.0.1)
        # OR use your EC2 instance's private IP (e.g., 10.0.x.x)
        proxy_pass http://172.17.0.1:5001; 
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}