server {
    listen 80;

    # 1. The React App (Fixes the refresh 404 bug!)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # If the file isn't found, give it to React Router to handle
        try_files $uri $uri/ /index.html; 
    }

    # 2. The Audio Traffic Cop (Takes the load off Express)
    location /audio/ {
        # Tells Nginx exactly where we mounted the volume in Docker
        alias /usr/share/nginx/html/media/audio/;
        # Allows browsers to scrub forward/backward in the audio player
        add_header Accept-Ranges bytes; 
    }
}
