import { query } from '../config/db.js';
import fs from 'fs';
import path from 'path';

// Helper function to safely delete files from the server
const deletePhysicalFile = (relativePath) => {
    if (!relativePath) return;
    try {
        // Use the exact base path where Multer saves the files
        const basePath = '/home/Shubham/YumeTunes/public';
        const absolutePath = path.join(basePath, relativePath);
        
        // I added a console.log here so you can verify the exact path in your terminal!
        console.log("Attempting to delete:", absolutePath);

        if (fs.existsSync(absolutePath)) {
            fs.unlinkSync(absolutePath);
            console.log("Successfully deleted:", absolutePath);
        } else {
            console.log("File not found on disk, skipping deletion.");
        }
    } catch (err) {
        console.error("Could not delete old file:", err);
    }
};

// === 1. GET ALL SONGS (For the SongManager Table) ===
const getAllSongs = async (req, res) => {
    try {
        const text = `
            SELECT s.id, s.title, s.cover_path, s.song_type, ar.name AS artist, a.title AS anime 
            FROM songs s
            JOIN artists ar ON s.artist_id = ar.id
            LEFT JOIN animes a ON s.anime_id = a.id
            ORDER BY s.id DESC
        `;
        const result = await query(text);
        res.status(200).json({ success: true, data: result.rows });
    } catch (err) {
        console.error("Error fetching all songs:", err);
        res.status(500).json({ success: false, message: 'Server error fetching songs' });
    }
};

// === 2. ADD A NEW SONG ===
const addSong = async (req, res) => {
    // These come from the formData.append() in your React component
    const { title, artist_name, anime_title, song_type, duration_seconds, genre } = req.body;
    
    try {
        if (!req.files || !req.files['audio_file']) {
            return res.status(400).json({ success: false, message: 'Audio file is required' });
        }

        // Get the paths generated by Multer
        const audioPath = `/audio/${req.files['audio_file'][0].filename}`;
        const coverPath = req.files['cover_image'] ? `/images/covers/${req.files['cover_image'][0].filename}` : null;

        // START TRANSACTION
        await query('BEGIN');

        // 1. Get or Create ARTIST
        const artistQuery = `
            INSERT INTO artists (name) VALUES ($1) 
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
        `;
        const artistRes = await query(artistQuery, [artist_name]);
        const artistId = artistRes.rows[0].id;

        // 2. Get or Create ANIME (Only if provided)
        let animeId = null;
        if (anime_title && anime_title.trim() !== "") {
            const animeQuery = `
                INSERT INTO animes (title, artist_id) VALUES ($1, $2) 
                ON CONFLICT (title) DO UPDATE SET title = EXCLUDED.title RETURNING id
            `;
            const animeRes = await query(animeQuery, [anime_title, artistId]);
            animeId = animeRes.rows[0].id;
        }

        // 3. Insert SONG
        const songQuery = `
            INSERT INTO songs (title, artist_id, anime_id, file_path, cover_path, song_type, duration_seconds) 
            VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
        `;
        // Make sure to capture the songId so we can link the genre!
        const songRes = await query(songQuery, [title, artistId, animeId, audioPath, coverPath, song_type, duration_seconds || null]);
        const songId = songRes.rows[0].id;

        if (genre && genre.trim() !== "") {
            // Insert the genre into the 'genres' table
            const genreQuery = `
                INSERT INTO genres (name) VALUES ($1) 
                ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
            `;
            const genreRes = await query(genreQuery, [genre.trim()]);
            const genreId = genreRes.rows[0].id;

            // Link the song and the genre in the 'song_genres' table!
            await query(`INSERT INTO song_genres (song_id, genre_id) VALUES ($1, $2)`, [songId, genreId]);
        }

        // COMMIT TRANSACTION
        await query('COMMIT');
        res.status(201).json({ success: true, message: 'Song added successfully' });

    } catch (err) {
        // IF ANYTHING FAILS, UNDO EVERYTHING
        await query('ROLLBACK');
        console.error("Error adding song:", err);
        res.status(500).json({ success: false, message: 'Server error saving song' });
    }
};

// === 3. UPDATE AN EXISTING SONG ===
const updateSong = async (req, res) => {
    const songId = req.params.id;
    const { title, artist_name, anime_title, song_type, duration_seconds, genre } = req.body;

    try {
        // 1. Fetch the current song to get existing file paths
        const currentSongRes = await query(`SELECT file_path, cover_path FROM songs WHERE id = $1`, [songId]);
        if (currentSongRes.rows.length === 0) {
            return res.status(404).json({ success: false, message: 'Song not found' });
        }
        const currentSong = currentSongRes.rows[0];

        // 2. Determine new file paths (use new ones if uploaded, otherwise keep old ones)
        let audioPath = currentSong.file_path;
        let coverPath = currentSong.cover_path;

        if (req.files && req.files['audio_file']) {
            audioPath = `/audio/${req.files['audio_file'][0].filename}`;
            deletePhysicalFile(currentSong.file_path); // Delete the old MP3
        }
        
        if (req.files && req.files['cover_image']) {
            coverPath = `/images/covers/${req.files['cover_image'][0].filename}`;
            deletePhysicalFile(currentSong.cover_path); // Delete the old Cover Image
        }

        // START TRANSACTION
        await query('BEGIN');

        // 3. Get or Create ARTIST
        const artistQuery = `
            INSERT INTO artists (name) VALUES ($1) 
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
        `;
        const artistRes = await query(artistQuery, [artist_name]);
        const artistId = artistRes.rows[0].id;

        // 4. Get or Create ANIME
        let animeId = null;
        if (anime_title && anime_title.trim() !== "") {
            const animeQuery = `
                INSERT INTO animes (title, artist_id) VALUES ($1, $2) 
                ON CONFLICT (title) DO UPDATE SET title = EXCLUDED.title RETURNING id
            `;
            const animeRes = await query(animeQuery, [anime_title, artistId]);
            animeId = animeRes.rows[0].id;
        }

        // 5. Update the SONG row
        const updateQuery = `
            UPDATE songs 
            SET title = $1, artist_id = $2, anime_id = $3, file_path = $4, cover_path = $5, song_type = $6, duration_seconds=$7
            WHERE id = $8
        `;
        await query(updateQuery, [title, artistId, animeId, audioPath, coverPath, song_type, duration_seconds, songId]);

        await query(`DELETE FROM song_genres WHERE song_id = $1`, [songId]);
        if (genre && genre.trim() !== "") {
            const genreQuery = `
                INSERT INTO genres (name) VALUES ($1) 
                ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id
            `;
            const genreRes = await query(genreQuery, [genre.trim()]);
            const genreId = genreRes.rows[0].id;

            await query(`INSERT INTO song_genres (song_id, genre_id) VALUES ($1, $2)`, [songId, genreId]);
        }

        // COMMIT TRANSACTION
        await query('COMMIT');
        res.status(200).json({ success: true, message: 'Song updated successfully' });

    } catch (err) {
        await query('ROLLBACK');
        console.error("Error updating song:", err);
        res.status(500).json({ success: false, message: 'Server error updating song' });
    }
};

// === 4. DELETE A SONG ===
const deleteSong = async (req, res) => {
    const songId = req.params.id;

    try {
        // 1. Fetch the song first so we know what files to delete from the hard drive
        const currentSongRes = await query(`SELECT file_path, cover_path FROM songs WHERE id = $1`, [songId]);
        
        if (currentSongRes.rows.length === 0) {
            return res.status(404).json({ success: false, message: 'Song not found' });
        }
        
        const { file_path, cover_path } = currentSongRes.rows[0];

        // 2. Delete the row from the database
        // Because you used ON DELETE CASCADE in your schema, this will automatically 
        // remove this song from user histories, playlists, and liked_songs!
        await query(`DELETE FROM songs WHERE id = $1`, [songId]);

        // 3. Clean up the physical files
        deletePhysicalFile(file_path);
        deletePhysicalFile(cover_path);

        res.status(200).json({ success: true, message: 'Song and associated files deleted' });

    } catch (err) {
        console.error("Error deleting song:", err);
        res.status(500).json({ success: false, message: 'Server error deleting song' });
    }
};

// === 5. UPDATE TIMED LYRICS ===
const updateLyrics = async (req, res) => {
    const songId = req.params.id;
    const { lyrics } = req.body;

    try {
        const updateQuery = `UPDATE songs SET lyrics = $1 WHERE id = $2`;
        await query(updateQuery, [lyrics, songId]);
        
        res.status(200).json({ success: true, message: 'Lyrics updated successfully' });
    } catch (err) {
        console.error("Error updating lyrics:", err);
        res.status(500).json({ success: false, message: 'Server error updating lyrics' });
    }
};

export default { getAllSongs, addSong, updateSong, deleteSong, updateLyrics };

